### ISSUE TITLE
Avoid unnecessary xxx*yyy style strings

### ISSUE THREAD

**Issue by yoid2000** [diffix/syndiffix#125]
Current implementation makes `xxx*yyy` type strings when the original string needs to be suppressed (where `xxx` is a possibly-null prefix, and `yyy` is a number.

The primary reason for this is to avoid releasing any strings that fail LCF. The problem is that we are too aggressive about this, and suppress strings that strictly speaking don't need to be suppressed. This happens because we partition a given columns values at 2dim and above.

What we should do instead is to use the 1dim tree to determine what the valid strings, and then at Ndim choose strings from the set of valid strings.

**Comment by cristianberneanu** [comment]
> What we should do instead is to use the 1dim tree to determine what the valid strings, and then at Ndim choose strings from the set of valid strings.

I think that, most of the time, there aren't any singularities in the corresponding 1-dim range. So we're left with 3 bad choices:
- we do the `prefix*number` stuff
- we output a generic placeholder, like `*` or `RARE_VALUE`
- we select a random singularity from that dimension
None of these are great solutions.

**Comment by yoid2000** [comment]
The case I'm most interested in is where all or nearly all of the 1dim values are singularities and pass LCF, but some of the Ndim values are not singularities. The problem I am running into now is that these few non-singularities cause ML measures to fail. In this case, I'd like to substitute the relatively small number of non-singularities with 1dim singularities (i.e. a close match...)

In the case you are thinking of (most of the 1dim values are non-singularities) then over the near-term we would still to `prefix*number` stuff. In the future, I'll make even these look more friendly but still without literally releasing the rare values.

**Comment by yoid2000** [comment]
By the way, this issue is for myself. I think it'll be a good first issue to work on, and then I can go through all the testing and build stuff

**Comment by cristianberneanu** [comment]
OK. I think this change could get a bit messy, so here is a hint:

The strings-to-integers mapping is done in a pre-processing step.
When generating string microdata, we don't have access to the corresponding tree node for a range, only to the previously computed mapping.

Probably the easiest way to approach this would be to also do a high-count test when encoding the strings as integers, and then randomly select one of the high-count strings from the given range when generating the corresponding microdata.

**Comment by yoid2000** [comment]
@cristianberneanu I think I mis-diagnosed the problem. I said this:

> This happens because we partition a given columns values at 2dim and above.

But this doesn't matter. At 2dim and above we are harvesting lower-dim nodes. If a 1dim node is a singularity, then that singularity value works its way up the tree ... it never merges with others. If a 1dim leaf node is not a singularity, then by definition all of its values fail LCF (otherwise it wouldn't be a leaf node ... it would have a child which is a singularity). In this case, the interval gets harvested.

Does this sound right to you?

If so, then what I probably want to do is, at microdata generation, check to see if only a small fraction of the rows are xxx*yyy nodes, and in that case simply assign these values to some non-supressed value. The idea here is that if most of the values are non-suppressed, then probably the row is categorical in any event, and we don't want to assign bogus values (messes up ML tasks). Also, if a small fraction is suppressed (i.e. 5% or less), then we won't have too much distortion by assigning them random non-suppressed values.

It seems that we need a post-microdata step, where we convert xxx*yyy values.

**Comment by cristianberneanu** [comment]
> Does this sound right to you?

Yes, that makes sense.

> Also, if a small fraction is suppressed (i.e. 5% or less), then we won't have too much distortion by assigning them random non-suppressed values.

I don't think doing this is a good idea: replacing suppressed values with random values will further distort the output. Probably better to replace them with `null` or `*` instead.

**Comment by yoid2000** [comment]
The problem is that replacing with NULL or * breaks ML software. I'd rather have the distortion than these kinds of errors...

(Well, maybe replacing with NULL doesn't break ML software, but any non-original string does break ML software)

**Comment by yoid2000** [comment]
Ok, I think the problem is the following (need to verify):

![image](https://github.com/diffix/syndiffix/assets/2162345/7b624b3b-4ae9-477f-aad0-eda417ec9dc9)


- A 1dim node X1 is a branch because it passes LCF. It's children X1.1 and X1.2 are singularities and also pass LCF.
- A 2dim node X2, for which X1 is a subnode, passes LCF. However, the children of X2 fail LCF. 
- As a result, when harvesting at X2, the children return nothing, and so the harvested buckets contain ranges (i.e. 0-1).
- What we really want is for the children of X2 to recognize that the singularities are in fact safe, and to return buckets with values 0 or 1.

**Comment by yoid2000** [comment]
One way to fix would be smarter harvesting.

Another way to fix would be smarter string assignment. We'd have to somehow recognize that the individual values are safe to assign from the 1dim tree....

**Comment by yoid2000** [comment]
Ok, now I'm not sure. Looking at the above picture, I would hope that the refine process would cause the singularities at the 1dim leaf nodes to be propagated up.

**Comment by yoid2000** [comment]
@cristianberneanu I'm trying to debug an issue whereby some columns have no `*` values when synthesized as a single column, but do have `*` values when synthesized along with other columns.

I can't figure out why it would happen. I thought for a short while earlier today that it might be because of what I explain above with the drawing, but after all I don't think that makes sense. Refinement should find the 1dim singularities (that pass LCF).

Don't spend any time on this, but if you have some immediate ideas I'd like to hear.

**Comment by cristianberneanu** [comment]
> Refinement should find the 1dim singularities (that pass LCF).

Yes, if all child nodes are low-count, the parent bucket should go into refinement and singularities should be produced from the 1-dim tree. But are you sure that both of them are low-count? Maybe only one of them is and adjustment is happening instead.

**Comment by yoid2000** [comment]
I'm not sure. I need to capture the event

**Comment by cristianberneanu** [comment]
Another cause might be that the refinement process fails for some reason and the bucket is left as it is.

**Comment by yoid2000** [comment]
Continued by #128
