### ISSUE TITLE
Never include AID columns in output

### ISSUE THREAD

**Issue by yoid2000** [diffix/syndiffix#25]
It occurs to me that we should not include AID columns in the output.

The main reason is that the AID columns has no value, but the user might not know this.

In particular, we don't capture any event information, for instance the distribution of rows over AIDs, or inter-event timing or sequences. But if we include some kind of AID column, then the user might assume that we do capture this stuff, and get bad results.

Until we implement event information, it seems it would be cleaner and clearer just to exclude the AID columns in the output.

**Comment by cristianberneanu** [comment]
The AID data is provided separately and caller is responsible of only providing the relevant data as input.
