### ISSUE TITLE
We don't detect datetimes properly

### ISSUE THREAD

**Issue by edongashi** [diffix/syndiffix#68]
File is `expedia_hotel_logs`, column `date_time`, I saw this result:

```
         log_id      date_time  ...  hotel_market  hotel_cluster
0  LOG_0076*532    2014-01-*86  ...            29             25
1    LOG_000*16     2014-0*393  ...           366             22
2   LOG_008*587  2014-08-1*424  ...           191             25
3   LOG_007*525  2014-07-1*265  ...           633             70
4   LOG_007*499  2014-07-1*291  ...            24             15
```

Suppression indicates it's parsed as string.

**Comment by cristianberneanu** [comment]
I can't reproduce the problem using my copies of the `expedia` and `taxi` datasets.
Edon, can you please post a small example input that shows the issue on your end?

**Comment by edongashi** [comment]
I'm trying to find the coresponding log files in SLURM and will try to get a stable reproduction.

**Comment by edongashi** [comment]
I see the problem. Date parsing is done in `example_simple.py`:

```py
# Try to infer datetime columns.
for col in df.columns[df.dtypes == "object"]:
    try:
        df[col] = pd.to_datetime(df[col])
    except (ParserError, ValueError):
        pass

return df
```

However, from SLURM I run the top level API directly without this wrapper. How should we handle this; do we parse in test script, or do we parse in the pipeline?

**Comment by cristianberneanu** [comment]
Ah, ok, now it makes sense why I couldn't reproduce it.

I think it makes more sense to leave this step in the responsibility of the callers: there will be various datetime formats involved, errors can appear during conversion, some data-sources will provide the correct column type, so no detection or conversion will be needed for them, and so on.

**Comment by edongashi** [comment]
Fixed in SLURM. Closing as completed.
