### ISSUE TITLE
Clustering solutions are worse than in the F# implementation.

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/syndiffix#74]
I was playing with a custom script that takes the first 50 K rows from the `taxi-one-day.csv` dataset and selects 5 specific columns for processing, and this is the output that I get:
```
Loaded 50000 rows. Columns:
0: pickup_longitude (float64)
1: pickup_latitude (float64)
2: fare_amount (float64)
3: rate_code (int64)
4: passenger_count (int64)

Fitting the synthesizer over the data...
Column clusters:
Initial= [2, 4]
Derived= (SHARED, [2], [0])
Derived= (SHARED, [2], [1])
Derived= (SHARED, [2], [3])
```
Notice how the initial cluster only has 2 columns in it.
The F# implementation produces this output:
```
=== Columns ===
  0 pickup_longitude (RealType); Entropy = 11.828231226413235
  1 pickup_latitude (RealType); Entropy = 11.799770332830937
  2 fare_amount (RealType); Entropy = 5.4025513988026965
  3 rate_code (IntegerType); Entropy = 0.2387340586221852
  4 passenger_count (IntegerType); Entropy = 0.6315105894728646
Assigning clusters...
Clusters: { InitialCluster = [|0; 1; 2|]
  DerivedClusters = [(Shared, [|2|], [|3|]); (Shared, [|2|], [|4|])] }.
```

**Comment by edongashi** [comment]
Interesting. It's expected for clustering to be worse since we run the solver for a fraction of the time, but this one seems that the dependence measure creates a barrier. The F# implementation literally has the solution as permutation `01234` (initial solution). And Python should have come up with that as well.

I have to take a closer look at dependence measure to see if there is a bug in the tree walk logic.

**Comment by edongashi** [comment]
Do you by chance have the dep. table for F# Cristian?

**Comment by cristianberneanu** [comment]
Yes, here it is:
```
Measuring dependence...
        0     1     2     3     4
 0   ----  0.27  0.16  0.02  0.02  = 0.47
 1   0.27  ----  0.16  0.02  0.03  = 0.47
 2   0.16  0.16  ----  0.06  0.03  = 0.42
 3   0.02  0.02  0.06  ----  0.01  = 0.10
 4   0.02  0.03  0.03  0.01  ----  = 0.09

 =   0.47  0.47  0.42  0.10  0.09
```

**Comment by edongashi** [comment]
Thanks. I will get a dump of Python's table and let's see how they compare.

**Comment by edongashi** [comment]
```
Loaded 50000 rows. Columns:
0: pickup_longitude (float64)
1: pickup_latitude (float64)
2: fare_amount (float64)
3: rate_code (int64)
4: passenger_count (int64)

Fitting the synthesizer over the data...
        0     1     2     3     4
 0   ----  0.01  0.09  0.01  0.02  = 0.13
 1   0.01  ----  0.10  0.01  0.03  = 0.15
 2   0.09  0.10  ----  0.02  0.06  = 0.26
 3   0.01  0.01  0.02  ----  0.00  = 0.04
 4   0.02  0.03  0.06  0.00  ----  = 0.11

 =   0.13  0.15  0.26  0.04  0.11
 ```
 
 The scores are much lower between 0,1,2...

**Comment by edongashi** [comment]
I have a feeling this bug is the key to bad scores. Something in the trees or maybe some dimension indexes are being mixed up. I have found no answer yet...

**Comment by edongashi** [comment]
Closed as complete, but this is not the cause of poor ML scores.
