### ISSUE TITLE
Add a notebook targeting the deployed library

### ISSUE THREAD

**Issue by edongashi** [diffix/syndiffix#85]

**Comment by yoid2000** [comment]
Some things to cover in the notebook:

Main points:

- Examples showing that the best way to get accuracy is to limit yourself to only the columns you want.
- Examples showing how to use the MLClustering to get better quality ML output
- Examples showing AID usage

Secondary:

- Example showing how to use default clustering and NoClustering, including how to get smaller clusters (and therefore faster execution).
- Example showing the effect of changing the seed

Tertiary (or probably a separate notebook):
- Example showing how to use syndiffix to create more or fewer rows (basically, make synthetic data then sample randomly as needed)

**Comment by cristianberneanu** [comment]
Paul, I suffered a bit from a lack of inspiration with regards to the content of the tutorial, but I now have a notebook that addresses the first point from your list.

I have assigned the PR to Edon, but you should have a look as well.
You can view the rendered notebook [here](https://github.com/diffix/syndiffix/blob/1eeddabc558d1738c0966a4902275317b231f3fa/docs/tutorial.ipynb).

I'll try to fit your second point in the same file as well, but I think AID usage is better left for a separate tutorial.

**Comment by yoid2000** [comment]
I'm fine with separate tutorials
