### ISSUE TITLE
Move to syndiffix repository once public

### ISSUE THREAD

**Issue by edongashi** [diffix/syndiffix#88]

**Comment by cristianberneanu** [comment]
We need to do this before setting the package publishing pipeline.
I will do the rename tonight (and also make this repo public).

**Comment by edongashi** [comment]
Do you want to do a repository move instead of just the data? Are we safe in reusing `syndiffix` name (which needs to be moved to `syndiffix-reference` or `syndiffix-fs`)...

**Comment by cristianberneanu** [comment]
I plan to do two renames:
1. `syndiffix` to `syndiffix-fs`
2. `syndiffix-py` to `syndiffix`
